# Generated by Django 4.2.7 on 2023-11-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_position_position_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='position_name',
            field=models.CharField(max_length=255),
        ),
    ]
